### PR TITLE
Wei recon demo

### PR DESCRIPTION
**Pull request by giltis**
added assistant function for vistrails demos. The addition provides the ability to search a tree for a specified file name, making demos more straight forward to use, and eliminating the requirement that source data paths be modified or altered in order to use the demos.

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @celiafish

**Comment by celiafish** [comment]
Gabe, this PR includes some functions irrelevant to my recon demo. Only vttools/vtmods/io.py contains FindData. All the others are new functions for FXI. Can you separate them and just include FindData, so we can move on to close PR of recon example. After this, can you create a new PR about new functions for FXI, and create a VisTrails workflow to test them? Thanks.

**Comment by giltis** [comment]
Yep, my mistake

**Comment by giltis** [comment]
Finally.

**Comment by celiafish** [comment]
Great. Will work on both tomorrow.

**Pull request merged**
